# Generated by Django 2.0.6 on 2018-07-03 15:39

from django.db import migrations, models
import dlibrary.models


class Migration(migrations.Migration):

    dependencies = [
        ('dlibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='myimg',
            field=models.ImageField(null=True, upload_to='images//', validators=[dlibrary.models.validate_img]),
        ),
    ]
