# Generated by Django 2.0.6 on 2018-07-23 09:27

from django.db import migrations, models
import dlibrary.models


class Migration(migrations.Migration):

    dependencies = [
        ('dlibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suser',
            name='myimg',
            field=models.ImageField(blank=True, default='static/images/images.png', null=True, upload_to='images\\', validators=[dlibrary.models.validate_img]),
        ),
    ]
