# Generated by Django 2.0.6 on 2018-07-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlibrary', '0002_book_myimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='attach1',
            new_name='attachment',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='myimg',
            new_name='image',
        ),
    ]
