# Generated by Django 2.0.6 on 2018-07-04 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dlibrary', '0003_auto_20180703_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlibrary.Branch'),
        ),
    ]
