# Generated by Django 2.0.6 on 2018-07-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlibrary', '0005_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='mobno',
            field=models.IntegerField(),
        ),
    ]
