# Generated by Django 2.0.6 on 2018-07-18 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlibrary', '0007_suser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suser',
        ),
    ]
